[project]
name = "open-webui-knowledge-sync"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "typer>=0.15.2",
]

[dependency-groups]
dev = [
    "open-webui>=0.5.20",
]
